version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    command: --default-authentication-plugin=mysql_native_password
  php:
    hostname: local_env
    build:
      context: ./
    volumes:
      - ./cms:/var/www/html
    ports:
      - 8080:80
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      PMA_HOSTS: "db"
    ports:
      - 8081:80
